### ISSUE TITLE
Practica 1

### ISSUE THREAD

**Issue by irving1989** [SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-30-bleachers#1]
[Reporte practica 1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-30-bleachers/files/12823306/Reporte.practica.1.pdf)

**Comment by Eve-lizet** [comment]
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
